### ISSUE TITLE
Multicast cannot be enabled on more than one Yggdrasil process (port reuse)

### ISSUE THREAD

**Issue by cwchristerw** [yggdrasil-network/yggdrasil-go#222] opened 2018-12-05 21:10 UTC
When running multiple instances in same machine, admin port should not be static. It would be nice increase by one when port is reserved instead of panic :smile:. Then should automatically change new free port to configuration. Could be temporarily fixed by editing config manually when first started.

2018/12/05 21:00:52 Starting up...
2018/12/05 21:00:52 Found 5 multicast interface(s)
2018/12/05 21:00:52 Starting switch
2018/12/05 21:00:52 Starting router
2018/12/05 21:00:52 Multicast discovery is enabled
2018/12/05 21:00:52 Failed to start multicast interface
2018/12/05 21:00:52 An error occurred during startup
panic: listen udp6 [::]:9001: bind: address already in use

goroutine 1 [running]:
main.main()
	/src/yggdrasil.go:227 +0x15bc

**Comment by cwchristerw** [comment] 2018-12-05 21:21
Correction: When changing port number from configuration manually doesn't work as expected AdminListen: tcp://localhost:9001 (usually) change to   AdminListen: tcp://localhost:9002 but still same error.
2018/12/05 21:19:31 Starting up...
2018/12/05 21:19:31 Found 5 multicast interface(s)
2018/12/05 21:19:31 Starting switch
2018/12/05 21:19:31 Starting router
2018/12/05 21:19:31 Multicast discovery is enabled
2018/12/05 21:19:31 Failed to start multicast interface
2018/12/05 21:19:31 An error occurred during startup
2018/12/05 21:19:31 Listening for TCP on: [::]:45097
panic: listen udp6 [::]:9001: bind: address already in use

goroutine 1 [running]:
main.main()
	/src/yggdrasil.go:227 +0x15bc

**Comment by neilalexander** [comment] 2018-12-05 22:02
Yes, the problem is indeed not the `Listen` or `AdminListen` ports, but the multicasting port.

I think it's probably possible to use `SO_REUSEPORT` (or whatever the Go equivalent is, if there is one) on the multicast socket to avoid this problem.

**Comment by neilalexander** [comment] 2018-12-06 22:42
Fixed by #223.

**Closed by neilalexander** 2018-12-06 22:42 UTC
Labels: bug
