### ISSUE TITLE
.rpm package broken?

### ISSUE THREAD

**Issue by ThomasLeister** [yggdrasil-network/yggdrasil-go#408] opened 2019-04-07 18:23 UTC
Hi,

i just tried to install Yggdrasil via the instructions on this page:

Unfortunately the sign key and the key provided in the instructions seem not to be the same. When installing, I get this error:

```
========================================================================================================
 Package                  Arch                  Version                  Paketquelle              Größe
========================================================================================================
Installieren:
 yggdrasil                x86_64                0.3.5-1                  yggdrasil                2.7 M

Transaktionsübersicht
========================================================================================================
Installieren  1 Paket

Gesamtgröße: 2.7 M
Installationsgröße: 6.8 M
Is this ok [y/d/N]: y
Downloading packages:
Warnung: /var/cache/yum/x86_64/7/yggdrasil/packages/yggdrasil-0.3.5-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, Schlüssel-ID d10b8f1a: NOKEY
Schlüssel wird von file:///etc/pki/rpm-gpg/RPM-GPG-KEY-yggdrasil geholt


Die aufgelisteten GPG-Schlüssel für die »Yggdrasil«-Paketquelle sind bereits installiert, aber sie sind nicht korrekt für dieses Paket.
Stellen Sie sicher, dass die korrekten Schlüssel-URLs für diese Paketquelle konfiguriert sind.


 Fehlgeschlagenes Paket: yggdrasil-0.3.5-1.x86_64
 GPG-Schlüssel sind konfiguriert als: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-yggdrasil
```

Is there a fix available? :-)

**Comment by neilalexander** [comment] 2019-04-07 18:31
Can you please confirm that `/etc/pki/rpm-gpg-RPM-GPG-KEY-yggdrasil` on your system matches the contents of https://neilalexander.s3.eu-west-2.amazonaws.com/deb/key.txt?

**Comment by ThomasLeister** [comment] 2019-04-07 18:50
Yes, the PGP key and contents are the same. 

Only on the server there's a gpg version header included:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQINBFqUDRcBEADZyoi72sFzaGHMpgHRT/XmtEVZJyvD28gMLKLmsSCjE2EEgwg6
wdflWoXzVHc+fPUuOdCqXjZcl8vRczkSpMsw60iMDuLMCQHXUQtwwFpp9FsTor4D
```

... which is not in the file on the webserver. ;-)

**Comment by cornfeedhobo** [comment] 2019-05-06 02:13
This is indeed broken. Looks like the package is not being signed.

**Comment by neilalexander** [comment] 2019-05-17 21:45
Sorry about the slow response to this. I've regenerated the packages in the S3 repository. Are they any better now?

We do actually have a new source RPM which I need to integrate into the CI builds. I really should get around to that - #420.

**Comment by ThomasLeister** [comment] 2019-05-18 05:24
Hi, I've tried again and ran `yum clean all` before installing.

```
Resolving Dependencies
--> Running transaction check
---> Package yggdrasil.x86_64 0:0.3.5-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================
 Package                                        Arch                                        Version                                      Repository                                      Size
==============================================================================================================================================================================================
Installing:
 yggdrasil                                      x86_64                                      0.3.5-1                                      yggdrasil                                      2.7 M

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 2.7 M
Installed size: 6.8 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/yggdrasil/packages/yggdrasil-0.3.5-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d10b8f1a: NOKEY                    ]  0.0 B/s |    0 B  --:--:-- ETA 
Public key for yggdrasil-0.3.5-1.x86_64.rpm is not installed
yggdrasil-0.3.5-1.x86_64.rpm                                                                                                                                           | 2.7 MB  00:00:00     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-yggdrasil


The GPG keys listed for the "Yggdrasil" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: yggdrasil-0.3.5-1.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-yggdrasil
```

Seems that there's still a signature error.

**Comment by neilalexander** [comment] 2019-05-18 09:39
Well I'm stumped. Bear in mind that this is actually a Debian machine I am using, but I can sign the RPMs and don't get any warning:
```
$ sh -c cd ~/rpm-repo/ && GPG_TTY=$(tty) rpm --addsign *.rpm
yggdrasil-0.3.5-1.arm64.rpm:
yggdrasil-0.3.5-1.armhf.rpm:
yggdrasil-0.3.5-1.i386.rpm:
yggdrasil-0.3.5-1.mips.rpm:
yggdrasil-0.3.5-1.mipsel.rpm:
yggdrasil-0.3.5-1.x86_64.rpm:
yggdrasil-develop-0.3.5-0027.arm64.rpm:
yggdrasil-develop-0.3.5-0027.armhf.rpm:
yggdrasil-develop-0.3.5-0027.i386.rpm:
yggdrasil-develop-0.3.5-0027.mips.rpm:
yggdrasil-develop-0.3.5-0027.mipsel.rpm:
yggdrasil-develop-0.3.5-0027.x86_64.rpm:
```
... and the packages are showing that they are signed:
```
rpm -qpi rpm-repo/yggdrasil-0.3.5-1.x86_64.rpm 
warning: rpm-repo/yggdrasil-0.3.5-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d10b8f1a: NOKEY
Name        : yggdrasil
Version     : 0.3.5
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Converted/contrib/net
Size        : 7159769
License     : see /usr/share/doc/yggdrasil/copyright
Signature   : RSA/SHA512, Sat 18 May 2019 10:23:43 BST, Key ID bc1bf63bd10b8f1a
Source RPM  : yggdrasil-0.3.5-1.src.rpm
Build Date  : Sun 28 Apr 2019 16:22:35 BST
Build Host  : 186dd78b7342
Relocations : (not relocatable)
Summary     : Yggdrasil Network
Description :
Yggdrasil is an early-stage implementation of a fully end-to-end encrypted IPv6
network. It is lightweight, self-arranging, supported on multiple platforms and
allows pretty much any IPv6-capable application to communicate securely with
other Yggdrasil nodes.
```
... but there is a `NOKEY` warning on those packages if I try to verify them locally:
```
$ rpm -v -K rpm-repo/yggdrasil-0.3.5-1.x86_64.rpm 
rpm-repo/yggdrasil-0.3.5-1.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID d10b8f1a: NOKEY
    Header SHA1 digest: OK (ca8e8648ea84e12472280b60d46c973dc81836d0)
    V4 RSA/SHA512 Signature, key ID d10b8f1a: NOKEY
    MD5 digest: OK (6c3b895a093b9b249dd5393798abd470)
```
... despite the fact that GPG clearly knows the key:
```
$ gpg --list-key d10b8f1a
pub   rsa4096 2018-02-26 [SC]
      569130E8CA20FBC4CB3FDE555898470A764B32C9
uid           [ultimate] deb.h-ic.eu
sub   rsa4096 2018-02-26 [S]
```
... and so does RPM:
```
$ rpm -qa --qf '%{SUMMARY}\n' gpg-pubkey*
gpg(deb.h-ic.eu)
```
To the best of my knowledge this used to work, and nothing has changed bar possible RPM or GPG upgrades on the box.

**Comment by Osndok** [comment] 2019-10-04 13:23
This sounds plausible, which might explain why the check fails on centos and not fedora:
* https://serverfault.com/questions/624888/bad-signatures-or-nokey-errors-on-rpms-i-just-signed

**Comment by neilalexander** [comment] 2019-11-20 14:13
Is this still happening?

**Comment by matkam** [comment] 2019-11-20 14:51
Yes it is. I’ve had to manually find and update the rpm package on my Amazon Linux server with the last few versions of Yggdrasil. There’s one more issue as well, preventing cleanup of the Yggdrasil package being replaced.

**Comment by neilalexander** [comment] 2019-11-20 15:02
Hm, okay, I'll take another look at the RPM signing. There must be something going on there.

**Comment by cornfeedhobo** [comment] 2020-03-11 07:16
@neilalexander this is still going on

**Comment by chrisnew** [comment] 2020-03-22 11:48
Confirmed, still going on.

**Comment by Saiv46** [comment] 2020-04-25 17:52
I was going to setup a OpenVZ hosting, but can't install Yggdrasil

**Comment by cornfeedhobo** [comment] 2023-06-04 15:13
@xloem it doesn't really resolve the issue - you've just opened your setup to middle man attacks. While unlikely, the signing should be fixed.

**Comment by neilalexander** [comment] 2023-10-21 19:49
Assumed out of date as we have RPMs on COPR.

**Closed by neilalexander** 2023-10-21 19:49 UTC
Labels: linux
