### ISSUE TITLE
Cgo multicast doesn't build on macOS 13

### ISSUE THREAD

**Issue by rex4539** [yggdrasil-network/yggdrasil-go#953] opened 2022-10-02 11:39 UTC
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/device/device_types.h:89:33: note: 'io_string_t' declared here
typedef char                    io_string_t[512];
                                ^

...

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
```

**Comment by neilalexander** [comment] 2022-10-02 11:44
You will need to provide more details than that. 

Which version of macOS, which version of Xcode and which version of Go?

**Comment by rex4539** [comment] 2022-10-02 11:46
macOS 13.0 (22A5358e)
Xcode 14.1 beta 3 (14B5033e)
go version go1.19.1 darwin/amd6

**Comment by neilalexander** [comment] 2022-10-02 11:49
I'm wondering if this is something to do with the macOS multicast code, can you try building with `CGO_ENABLED=0`?

Failing that, it looks like there's something in the macOS SDK, so would recommend you try with a release version like Xcode 14.0.1.

**Comment by rex4539** [comment] 2022-10-02 11:52
> I'm wondering if this is something to do with the macOS multicast code, can you try building with `CGO_ENABLED=0`?

This worked.

**Comment by neilalexander** [comment] 2022-10-02 11:57
OK, glad to hear it. Will keep this issue open and rename it.

**Comment by neilalexander** [comment] 2023-10-21 20:17
Closing as out-of-date.

**Closed by neilalexander** 2023-10-21 20:17 UTC
Labels: macos

**Comment by rex4539** [comment] 2023-10-22 06:08
Nope. It's still up to date.

**Comment by neilalexander** [comment] 2023-10-22 08:43
I can't reproduce on three different systems — either there is something wrong with your Xcode/SDKs install, or you have out-of-date binaries in your Go toolchain. Try updating to the most recent Go version and then reinstalling `gomobile` afterwards.
