### ISSUE TITLE
Add config option to disable debug api

### ISSUE THREAD

**Issue by errhammr** [yggdrasil-network/yggdrasil-go#810] opened 2021-07-10 21:58 UTC
The debug api (`debug_remote*` commands) are a privacy concern as they allow the spanning tree to be traversed and devices to be discovered that some users might not want to be publicly visible. There should be a well documented config option to disable it for those who choose to do so.

In the mean time, concerned users can disable the debug api by commenting out the relevant lines in `src/core/api.go`, e.g. by applying the following patch and recompiling yggdrasil:

```diff
diff --git a/src/core/api.go b/src/core/api.go
index 05d9f36..9bf2f31 100644
--- a/src/core/api.go
+++ b/src/core/api.go
@@ -285,6 +285,7 @@ type AddHandler interface {
 // SetAdmin must be called after Init and before Start.
 // It sets the admin handler for NodeInfo and the Debug admin functions.
 func (c *Core) SetAdmin(a AddHandler) error {
+/*
        if err := a.AddHandler("getNodeInfo", []string{"key"}, c.proto.nodeinfo.nodeInfoAdminHandler); err != nil {
                return err
        }
@@ -297,5 +298,6 @@ func (c *Core) SetAdmin(a AddHandler) error {
        if err := a.AddHandler("debug_remoteGetDHT", []string{"key"}, c.proto.getDHTHandler); err != nil {
                return err
        }
+*/
        return nil
 }
```

**Comment by neilalexander** [comment] 2021-07-10 22:51
It should be noted that this is not specifically new — in v0.3 and earlier the DHT itself could be crawled and this is how we generate the network maps. In v0.4 the DHT is no longer crawlable but we still want to be able to see how the network performs as it grows, hence the debug query calls.

These do reveal relationships between public keys but shouldn't reveal much else (they don't reveal real world IP addresses, for example) and certainly won't be present in a future v1.0 release.

**Comment by Arceliar** [comment] 2021-07-10 23:32
I don't believe this change would prevent your node from responding to lookups, it would just prevent it from sending lookups of its own.

All of the `debug_remote*` functions are temporary, and we intend to remove them at some point, and probably transitioning through an optional phase where it's enabled-by-default first (and then disabled-by-default). In the mean time, they're useful for debugging, so it would potentially make it harder to diagnose and fix issues if we made them optional at this stage.

It's worth mentioning that ygg *cannot* be anonymous by design; the routing scheme *must* expose who some of your peers are, at least to some other nodes in the network, and who you're talking to (to be able to route traffic). It's not intended to be any more anonymous than standard IP, so if anonymity is your concern, then you probably need to handle that at some other layer of your network stack.

**Comment by zander** [comment] 2021-07-11 10:11
I think the main question about the debug API (vs the ygg design) are;

* can someone join the yggdrasil network and get notifications about my turning on my laptop / phone.
* can my device that always peers to the same public node be located physically as I travel.
* ditto, but I now have some smart peer selection based on ping times.

And to follow up based on likely answer;

* since a peer is trackable by their public key, is it harmful to Yggdrasil in any way if a peer on-the-edge creates a new private key every time they turn on their machine?

**Comment by neilalexander** [comment] 2021-07-24 22:16
> can someone join the yggdrasil network and get notifications about my turning on my laptop / phone.

Not in realtime, no. If they knew your public key or IP address then they could send periodic/continuous traffic to you anyway to see if you respond.

> can my device that always peers to the same public node be located physically as I travel

Not really. There isn’t really anything to correlate your real location with your peer locations since peering is possible over the internet and peers could be anywhere.

> since a peer is trackable by their public key, is it harmful to Yggdrasil in any way if a peer on-the-edge creates a new private key every time they turn on their machine?

Not at all, you can do this by simply removing the `PrivateKey` option from your config file altogether. Yggdrasil will generate a new key each time the process starts up. You will get a new IP address as a result, so in that regard it is a lot like having a dynamic IP from an ISP.

**Comment by neilalexander** [comment] 2023-10-21 19:57
Closing as out-of-date.

**Closed by neilalexander** 2023-10-21 19:57 UTC
