### ISSUE TITLE
Yggdrasil periodically disconnection

### ISSUE THREAD

**Issue by ne-vlezay80** [yggdrasil-network/yggdrasil-go#564] opened 2019-10-02 16:27 UTC
Log:
```
сен 30 07:54:24 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:24 Failed to accept connection: accept tcp [fe80::340a:8d3:7640:fbd%wlx503eaa342a64]:3616
сен 30 07:54:24 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:24 Stopping TCP listener on: [fe80::340a:8d3:7640:fbd%wlx503eaa342a64]:36169
сен 30 07:54:25 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:25 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::5cdb:5215:89d0:c28
сен 30 07:54:26 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:26 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::5cdb:5215:89d0:c28
сен 30 07:54:27 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:27 Listening for TCP on: [fe80::5cdb:5215:89d0:c28c%wlx503eaa342a64]:35165
сен 30 07:54:27 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:27 Connected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::6efd:b9ff:fe63:1bb3%wlx503e
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:e64d:1a9:d2b0:9c74:f285:ea73:5e05@188.226.125.64, source 192.168
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::664:d81f:30f1:2481%wlx50
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@94.181.44.207, source 192.168.
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.177.21.156, source 192.16
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 200:1e4b:b2df:69ba:1eba:fdf9:edde:3712@78.155.207.12, source 192.168
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 201:195b:52d2:285e:d4b1:a4f1:2f77:42a@195.211.160.2, source 192.168.
сен 30 07:56:33 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:33 Failed to accept connection: accept tcp [fe80::5cdb:5215:89d0:c28c%wlx503eaa342a64]:35
сен 30 07:56:33 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:33 Stopping TCP listener on: [fe80::5cdb:5215:89d0:c28c%wlx503eaa342a64]:35165
сен 30 07:56:34 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:34 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::340a:8d3:7640:fbd%
сен 30 07:56:35 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:35 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::340a:8d3:7640:fbd%
сен 30 07:56:36 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:36 Listening for TCP on: [fe80::340a:8d3:7640:fbd%wlx503eaa342a64]:42149
сен 30 07:56:37 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:37 Connected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::664:d81f:30f1:2481%wlx503ea
сен 30 07:57:01 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:01 Connected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@94.181.44.207, source 192.168.0.1
сен 30 07:57:01 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:01 Connected TCP: 201:e64d:1a9:d2b0:9c74:f285:ea73:5e05@188.226.125.64, source 192.168.0.
сен 30 07:57:01 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:01 Connected TCP: 200:1e4b:b2df:69ba:1eba:fdf9:edde:3712@78.155.207.12, source 192.168.0.
сен 30 07:57:01 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:01 Connected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.177.21.156, source 192.168.0
сен 30 07:57:01 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:01 Connected TCP: 201:195b:52d2:285e:d4b1:a4f1:2f77:42a@195.211.160.2, source 192.168.0.1
сен 30 07:57:58 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:58 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@94.181.44.207, source 192.168.
сен 30 07:57:58 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:57:58 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::664:d81f:30f1:2481%wlx50
сен 30 07:58:32 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:58:32 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::6efd:b9ff:fe63:1bb3%wlx5
сен 30 07:58:42 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:58:42 Connected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::664:d81f:30f1:2481%wlx503ea
lines 2981-3031/3031 (END)
```
Version: 0.3.9

**Comment by Arceliar** [comment] 2019-10-04 02:06
The log lines are truncated, so they're missing the part that says what the error is. A debug log may help, with `./yggdrasil -logging "info,warn,error,debug"`, and then posting the full log lines (not truncated to the first ~160 characters).

Do you know how to reproduce this on other machines? It's hard to debug these sorts of things if we can't reproduce it locally.

For now I'm just looking through the parts of the log I can see, and speculating as to what's happening:
```
сен 30 07:54:24 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:24 Failed to accept connection: accept tcp [fe80::340a:8d3:7640:fbd%wlx503eaa342a64]:3616
сен 30 07:54:24 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:24 Stopping TCP listener on: [fe80::340a:8d3:7640:fbd%wlx503eaa342a64]:36169
сен 30 07:54:25 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:25 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::5cdb:5215:89d0:c28
сен 30 07:54:26 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:26 Not multicasting on wlx503eaa342a64 due to error: listen tcp [fe80::5cdb:5215:89d0:c28
сен 30 07:54:27 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:27 Listening for TCP on: [fe80::5cdb:5215:89d0:c28c%wlx503eaa342a64]:35165
сен 30 07:54:27 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:54:27 Connected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::6efd:b9ff:fe63:1bb3%wlx503e
```
It looks like something happened to the `wlx503eaa342a64` and a connection failed. This normally happens when the interface goes offline, but it's possible there could be other reasons. It then tries to start a listener once per second for the next 3 seconds. The first two times it fails ("Not multicasting") for some reason, which was cut off by the log. The third time, it succeeds, but I notice that it's now listening with a different address. It then connects to a node on the local network.

Next we have a little less than 2 minutes of silence before this:
```
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:e64d:1a9:d2b0:9c74:f285:ea73:5e05@188.226.125.64, source 192.168
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@fe80::664:d81f:30f1:2481%wlx50
сен 30 07:56:20 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:20 Disconnected TCP: 201:9316:3c04:f29:d5aa:20a0:c5ee:bc0b@94.181.44.207, source 192.168.
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.177.21.156, source 192.16
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 200:1e4b:b2df:69ba:1eba:fdf9:edde:3712@78.155.207.12, source 192.168
сен 30 07:56:21 evgeny-M61PME-S2P yggdrasil[15648]: 2019/09/30 07:56:21 Disconnected TCP: 201:195b:52d2:285e:d4b1:a4f1:2f77:42a@195.211.160.2, source 192.168.
```
This is important, because we close a connection after 2 minutes without receiving any traffic (including protocol / keep-alive traffic). So this tells me that at around 2 minutes earlier (about the same time the multicast listener was killed), these TCP connections stopped sending any traffic to the node, and this is when it finally decided that they have timed out and closed the connection.

I'm not sure what the event was that caused the problems for that interface. Since the there were two "Not multicasting" lines, that tells me the interface was up (at least long enough to see it and try to listen), but binding a socket failed for some reason -- maybe the OS has a limit on the number of open sockets? But that wouldn't explain why the existing connections would stall. The only thing I can think of that would reproduce this behavior is if the interface was brought down and then brought back up, and when it was brought back up its IP address changed, so the existing connections just sit there for 2 minutes until they time out. But I would not expect that to affect v0.3.9 and not also affect all prior versions (and basically all other applications on the machine).

**Comment by yujiri8** [comment] 2020-05-16 03:03
I'm getting similar output on v0.3.14; mine isn't truncating the output and the errors are all "message error: EOF". Here's an excerpt:
```
2020/05/16 02:40:49 Build name: yggdrasil
2020/05/16 02:40:49 Build version: 0.3.14
2020/05/16 02:40:49 Starting up...
2020/05/16 02:40:49 Starting switch
2020/05/16 02:40:49 Starting router
2020/05/16 02:40:49 Startup complete
2020/05/16 02:40:49 Starting multicast module
2020/05/16 02:40:49 Listening for TCP on: [fe80::1%lo0]:55459
2020/05/16 02:40:49 Interface name: /dev/tun0
2020/05/16 02:40:49 Interface IPv6: 200:d417:61d3:dbab:ac0c:9cbe:d4fc:e22d/7
2020/05/16 02:40:49 Interface MTU: 32767
2020/05/16 02:40:49 Error in SIOCSIFADDR_IN6: invalid argument
2020/05/16 02:40:49 Using ifconfig as fallback: ifconfig /dev/tun0 inet6 200:d417:61d3:dbab:ac0c:9cbe:d4fc:e22d/7
2020/05/16 02:40:49 UNIX admin socket listening on /var/run/yggdrasil.sock
2020/05/16 02:40:49 Listening for TCP on: [fe80::c8f7:ebff:fed2:c61f%vtnet0]:22822
2020/05/16 02:40:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:40:49 Your IPv6 address is 200:d417:61d3:dbab:ac0c:9cbe:d4fc:e22d
2020/05/16 02:40:49 Your IPv6 subnet is 300:d417:61d3:dbab::/64
2020/05/16 02:40:49 Connected TLS: 201:a7a3:e92e:ab23:19be:c3ca:6605:1211@67.205.187.55, source 142.93.116.17
2020/05/16 02:41:16 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:41:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:42:04 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:42:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:43:06 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:43:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:44:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:44:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:45:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:45:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:46:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:46:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:47:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:47:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:48:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:48:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:49:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:49:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:50:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:50:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:51:07 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:51:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:52:06 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:52:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:53:08 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:53:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:54:00 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:54:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:54:59 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:55:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:56:01 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:56:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:57:03 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:57:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:58:05 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:58:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 02:59:07 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 02:59:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 03:00:09 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
2020/05/16 03:00:49 Connected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17
2020/05/16 03:00:58 Disconnected TCP: 201:4859:795c:165f:1969:6339:9aa9:ac39@45.77.107.150, source 142.93.116.17; error: message error: EOF
```

**Comment by cwchristerw** [comment] 2020-05-24 18:36
yujiri8, this happens to me also. I remember time when i didnt have issues with connections. This has happened since 0.3.8, i think.

**Comment by aabbdev** [comment] 2021-10-01 17:52
![Capture d’écran du 2021-10-01 19-52-31](https://user-images.githubusercontent.com/30107107/135665367-55b70d8f-9cb2-44e3-a784-476a4e3b4e3c.png)

**Comment by aabbdev** [comment] 2021-10-01 17:52
same problem

**Comment by aabbdev** [comment] 2021-10-01 17:53
![Capture d’écran du 2021-10-01 19-53-21](https://user-images.githubusercontent.com/30107107/135665486-e6759f8c-75cd-4acd-8d00-4c387261da99.png)

**Comment by neilalexander** [comment] 2023-10-21 19:54
Closing as out-of-date.

**Closed by neilalexander** 2023-10-21 19:54 UTC
