### ISSUE TITLE
yggdrasil constantly disconnecting, renders it unusable

### ISSUE THREAD

**Issue by chymian** [yggdrasil-network/yggdrasil-go#937] opened 2022-08-30 08:19 UTC
hi,
yggdrasil is steadily disconnecting from the peers, rendering it unusable.
log see below.
pings are behaving accordingly to the logged disconnects.

when I first started using ygg, ca. 6 - 12M ago, it worked reliable, even as transport for my ssh-sessions to the hosts. 
since a while now (AFAIR ~<6M), it's having these connection pbls, while my wireguard VPN, which runs in paralell, still works as expected.
I could understand, when the LTE-based network has some congestions/net-pbls, from time to time, but there is no reason for the both DC-based servers.

for any logs/traces you need, let me know

### setup:
1 ubuntu 20.04, server
ygg: 0.4.3
runs in DataCenter, 1GBs

1 debian bullseye, server
ygg: 0.4.4
runs in DataCenter, 1GBs

1 laptop, bullseye
ygg: 0.4.4
runs on 4G/LTE Wifi

the logs get spamed with messages like this on all hosts:
```

Aug 30 10:56:59 hostname yggdrasil[843]: 2022/08/30 08:56:59 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: read tcp 63.250.xx.xxx:7443->27.55.xx.xx:47455: i/o timeout
Aug 30 10:58:12 hostname yggdrasil[843]: 2022/08/30 08:58:12 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
Aug 30 10:59:02 hostname yggdrasil[843]: 2022/08/30 08:59:02 Disconnected TLS: 200:d87e:39e:2bd6:dd2e:c556:83b1:5fa4@65.108.215.84, source 63.250.xx.xxx; error: EOF
Aug 30 11:00:17 hostname yggdrasil[843]: 2022/08/30 09:00:17 Connected TLS: 200:d87e:39e:2bd6:dd2e:c556:83b1:5fa4@65.108.215.84, source 63.250.xx.xxx
Aug 30 11:01:31 hostname yggdrasil[843]: 2022/08/30 09:01:31 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: read tcp 63.250.xx.xxx:7443->27.55.xx.xx:32543: i/o timeout
Aug 30 11:02:18 hostname yggdrasil[843]: 2022/08/30 09:02:18 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
Aug 30 11:03:19 hostname yggdrasil[843]: 2022/08/30 09:03:19 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: read tcp 63.250.xx.xxx:7443->27.55.xx.xx:24460: i/o timeout
Aug 30 11:04:12 hostname yggdrasil[843]: 2022/08/30 09:04:12 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
Aug 30 11:04:59 hostname yggdrasil[843]: 2022/08/30 09:04:59 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: read tcp 63.250.xx.xxx:7443->27.55.xx.xx:11605: i/o timeout
Aug 30 11:06:15 hostname yggdrasil[843]: 2022/08/30 09:06:15 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
Aug 30 11:06:48 hostname yggdrasil[843]: 2022/08/30 09:06:48 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: EOF
Aug 30 11:07:11 hostname yggdrasil[843]: 2022/08/30 09:07:11 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
Aug 30 11:11:10 hostname yggdrasil[843]: 2022/08/30 09:11:10 Disconnected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx; error: read tcp 63.250.xx.xxx:7443->27.55.xx.xx:12608: i/o timeout
Aug 30 11:12:16 hostname yggdrasil[843]: 2022/08/30 09:12:16 Connected TLS: 202:4799:7217:f014:e723:5f61:da03:5a@27.55.xx.xx, source 63.250.xx.xxx
```
edit1: changed log to more complete output

**Comment by neilalexander** [comment] 2022-09-24 13:13
What is the latency between these nodes?

**Comment by chymian** [comment] 2022-09-24 14:33
between debian (hetzner, Helsinki) & ubuntu (SSDnodes, Amsterdam) 27 - 29 ms

**Comment by neilalexander** [comment] 2022-09-24 14:34
OK, and is there a firewall on either end that could be timing out the connections?

(i.e. something that isn't tracking connection state properly and terminating the TCP/TLS connections after a period of time)

**Comment by chymian** [comment] 2022-09-24 14:44
there a FWs on both ends:
Debian runs the famous proxmox virtualisation server and the VM's/Services it's providing are running without any pbls.
on the ubuntu side: there is a cloudron server running and serving around 2 dozend different Apps without problems since 5 years.

and as I mentioned, the pbls started some month ago, while the server are running since years.

**Comment by POMATu** [comment] 2022-10-05 23:22
got same problem on my setup. Issue happened even between local yggdrasil nodes they ALL were disconnecting at the same time. Issue was not related to timing, its only happened when I run speedtest.net in browser and induced load onto my internal mesh setup.

Then suddenly i started running ping on gateway during speedtest.net-over-yggdrasil load and noticed that whole underlying wireguard tunnel that im using on gateway for internet was freezing during that test.
I disabled wireguard tunnel and problem gone away. No any yggdrasil node disconnecting now, not locally nor remote nodes

I think this is related to some MTU issues inside or outside wireguard tunnel. I also had same issues when tried to do udp openvpn over this particular wg tunnel. When i switched those vps to TCP problem with vpn gone away because TCP can auto adjust MTU

But can yggdrasil autoadjust that? Uno its not just my shitty setup it can happen when ISP gets on crack.
My wireguard setup cant be wrong its as simple as fuck. I believe this is some connectivity issues between datacenters im using related to MTU problems

If you are using any underlying UDP tunnels for internet or for yggdrasil try disabling them or switching to some openvpn TCP

> while my wireguard VPN, which runs in paralell, still works as expected.
bro try without it even if it doesnt tampers default gateway (Table=Off). This issue made me nuts but turned out wg doing some strange shit again

**Comment by rkfg** [comment] 2022-10-11 07:43
I think if it can be reproduced reliably and quickly without much bandwidth usage, a Wireshark log can help. It highlights TCP issues (duplicates, retransmissions etc.) with different colors so it's easy to spot them in the capture. Also see if there are blocked ICMP packets, MTU can indeed be a problem but if ICMP is partially blocked that can cause issues too. Could be easy to record traffic to a file with `tcpdump` on both ends, then analyze it locally with Wireshark.

**Comment by majestrate** [comment] 2022-10-11 14:20
as @POMATu pointed out tcp/443 for peering may help. if it does that will highlight the cause of this underlying issue is the ISP, otherwise it is MUCH more likely caused by an yggdrasil bug. more data points can help.

**Comment by POMATu** [comment] 2022-10-11 16:59
A bit of update, for some reason disabling wireguard helped for a day then problem emerged again

And my question was skipped I shall ask again:
Does yggdrasil fixes MTU problems like openvpn tcp does? I am not sure if its done on TCP layer or needs to be implemented in software. Need to know if I should exclude this by deduction

> Also see if there are blocked ICMP packets, MTU can indeed be a problem but if ICMP is partially blocked that can cause issues too.
ICMP was blocked indeed on that server where I got constant drops of all nodes in all VMs all at the same time. Could you please elaborate how does ICMP affects yggdrasil and why openvpn-tcp is not affected by that? (it doesnt reconnects)
Kindly also elaborate where ICMP should be unblocked. Should it be unblocked on all VMs running yggdrasil or also on gateway for some reason?
I will try putting yggdrasil nodes away from all firewalls for a test on separate vms

> (duplicates, retransmissions etc.)
So what if it has retransmissions? What is the problem with that? Its supposed to retransmit and not drop connection

> if it does that will highlight the cause of this underlying issue is the ISP
ISP or not if we talking about topic starter that could be a reason. But im getting same issues in virtualized network, that one is bridged with windows vmware hostonly bridge so could be anything

but even tho there can be some problem with some fucked setup the point is yggdrasil has to work over such shitty connections. Openvpn-tcp works just fine and yggdrasil is a mesh network for doomsday it needs to work even better than openvpn, diversified, fast-reconnecting, without inner-layer timeouts/drops
Like for example why its taking 5 seconds to reestablish dropped connections? It takes so long that speedtest.net goes on timeout with error. This is definitely not as I see stable mesh network

And yh I think ISPs can get even shittier with crisis if they dont feel too shit for you right now due to integrated DPIs

**Comment by neilalexander** [comment] 2023-10-21 20:17
Closing as this looks like an environmental issue.

**Closed by neilalexander** 2023-10-21 20:17 UTC
