### ISSUE TITLE
Testing yggdrasil on macOS 10.13.5 (17F77), ping to local ipv6 fails

### ISSUE THREAD

**Issue by satindergrewal** [yggdrasil-network/yggdrasil-go#131] opened 2018-06-15 08:40 UTC
Using latest darwin binary from here:
https://circleci.com/api/v1.1/project/github/yggdrasil-network/yggdrasil-go/latest/artifacts

binary link: https://156-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.2.22-darwin-amd64

- downloaded bin to `~/Downloads` directory
- renamed and changed it's permissions to executable
- generated conf file
- started with sudo command like this:

```shell
$ sudo ./yggdrasil -useconf < yggdrasil.conf 
2018/06/15 20:14:04 Starting up...
2018/06/15 20:14:04 Found 10 multicast interface(s)
2018/06/15 20:14:04 Starting router
2018/06/15 20:14:04 Multicast discovery is enabled
2018/06/15 20:14:04 Listening for TCP on: [::]:36845
2018/06/15 20:14:04 Interface name: utun3
2018/06/15 20:14:04 Interface IPv6: 203:5af4:178a:4da5:dbd:5380:32e3:47ed/7
2018/06/15 20:14:04 Interface MTU: 65535
2018/06/15 20:14:04 Startup complete
2018/06/15 20:14:04 Your IPv6 address is 203:5af4:178a:4da5:dbd:5380:32e3:47ed
2018/06/15 20:14:04 Your IPv6 subnet is 303:5af4:178a:4da5::/64
2018/06/15 20:14:04 Admin socket listening on 127.0.0.1:9001
```

- from other terminal tab, tried to ping to local IPv6 with 100% packet loss

```shell
$ ping6 203:5af4:178a:4da5:dbd:5380:32e3:47ed
PING6(56=40+8+8 bytes) 203:5af4:178a:4da5:dbd:5380:32e3:47ed --> 203:5af4:178a:4da5:dbd:5380:32e3:47ed
^C
--- 203:5af4:178a:4da5:dbd:5380:32e3:47ed ping6 statistics ---
34 packets transmitted, 0 packets received, 100.0% packet loss

$ ping6 203:5af4:178a:4da5:dbd:5380:32e3:47ed
PING6(56=40+8+8 bytes) 203:5af4:178a:4da5:dbd:5380:32e3:47ed --> 203:5af4:178a:4da5:dbd:5380:32e3:47ed
^C
--- 203:5af4:178a:4da5:dbd:5380:32e3:47ed ping6 statistics ---
8 packets transmitted, 0 packets received, 100.0% packet loss

$ ping6 203:5af4:178a:4da5:dbd:5380:32e3:47ed
PING6(56=40+8+8 bytes) 203:5af4:178a:4da5:dbd:5380:32e3:47ed --> 203:5af4:178a:4da5:dbd:5380:32e3:47ed

```

Going to try doing ping to other IPv6 after testing peering.

-- Satinder

**Comment by Arceliar** [comment] 2018-06-16 16:00
In [peer.go](https://github.com/yggdrasil-network/yggdrasil-go/blob/0ec5f1c02c71e8afae7a0fde4d69a600460cdb6a/src/yggdrasil/peer.go#L237-L239) packets are dropped if they would be routed back to the same peer. The self node appears as peer 0. So if traffic to yourself gets sent to the the tun device on osx, then it would get dropped here (more likely, it gets dropped earlier because no session is set up, because the initial DHT lookup and session setup traffic gets dropped here).

I don't have a mac to test on, but I think that's possibly where the problem is.

The only reason to drop packets there is to prevent transient routing loops where A sends a routing update to B, and before B receives it, B sends some packets to A. A may then need to send those packets back to B. B is guaranteed to receive A's routing update and process it before any of the returned packets (since v0.2), so the loop should only be one cycle, but I like to be overly cautious about routing loops. This check would probably need to be dropped or changed as part of #111 if we go that route, or we may want to drop it anyway if it's no longer required, but it needs testing. If we need to keep that check in peer.go for some reason, then we could possibly insert a bypass into either the tun/tap or router code, which would immediately return packets to the tun/tap device in this case, but that's a little messy in other ways.

**Comment by neilalexander** [comment] 2018-06-16 16:08
Indeed, packets to the local IPv6 address do appear to be sent to the TUN device, as shown by tcpdump.

This is one of those bugs that is a bit more of an inconvenience - it will mostly affect people who run a service that listens specifically on the Yggdrasil address, and then try to access it locally from the same system.

Seems a little silly to break the router logic for this - should `tun.go` just mirror it back?

**Comment by Arceliar** [comment] 2018-06-16 16:14
If it's failing for the reason I think, then the place where it's being dropped *shouldn't* be a problem anymore since the v0.2 change. If that's the case, then I want to remove that check anyway. It would save packets from being dropped if they're sent to a peer after that peer's coords change and before we are made aware of the change. But I want to come up with a way to test that this actually works first.

I am OK if the tun returns the packet for now. We may want to remove that mirror later if the routing problem is fixed (though the mirror would still be faster--bypassing crypto, etc). It's annoying that the OS doesn't recognize that it's sending a packet to itself in this case.

**Comment by neilalexander** [comment] 2018-07-07 21:52
This is fixed in `develop` with the new switch changes.

**Closed by neilalexander** 2018-07-07 21:52 UTC
Labels: bug, macos
