### ISSUE TITLE
[Feature Request] every node can play as a STUN/TURN server for higher bandwidth

### ISSUE THREAD

**Issue by xialvjun** [yggdrasil-network/yggdrasil-go#1060] opened 2023-09-08 12:33 UTC
Now the data in the yggdrasil network is send across many nodes. `A <-> D` may be `A <-> B <-> C <-> D` in the real network. This makes yggdrasil self healing, but also **lower bandwidth**. 

What if B or C act as a STUN/TURN server? 

After `A <-> B <-> C <-> D` connection is created:
```
A: hey, D, have you enabled public_real_network_address?
D: yes. xxxxxxxxxx is my real_network_address, what's your's?
A: it's yyyyyyyyyyy.
```

Then `A <-> D` connection is created, but in user space, they are the same connection. App will get higher bandwidth.

Of course, if it find `A <-> D` is broken (by whatever reasons, like censorship), yggdrasil can auto changed to `A <-> B <-> D` (if B has enabled public_real_network_address) or `A <-> C <-> D` (C has enabled it) or `A <-> B <-> C <-> D`.

Enable `public_real_network_address` will run the risk of widely exposed your IP.

**Comment by xialvjun** [comment] 2023-09-08 12:34
https://github.com/yggdrasil-network/yggdrasil-go/issues/778#issuecomment-1711571270 

This may be the same feature request.

**Comment by neilalexander** [comment] 2023-09-08 12:40
Simple answer of why we don't do this is because the whole purpose of Yggdrasil is to figure out how to efficiently route _with the links we have been given_.

If we add mechanisms to facilitate new peerings automatically then we are changing the scope of the project significantly and we are no longer testing the same thing anymore.

Yggdrasil is an overlay over the internet because it is convenient for experimenting at scale, not because that's how the project really should continue long-term. We care about the peering topology only, we are not aware of topology under that by design.

**Comment by xialvjun** [comment] 2023-09-08 13:21
But if without this, after yggdrasil been more popular, no community public peers can afford that big network traffic.

**Comment by xialvjun** [comment] 2023-09-08 14:05
We could have static peers and dynamic/temporary peers. Temporary peers will be removed after the last APP connection is disconnected. This shouldn't affect nodes connecting to each other. Or even we can let connection must be made by static peers, then the other traffic can use temporary peers. Maybe I'm too naive.😔

**Comment by one-d-wide** [comment] 2023-09-08 14:42
If you want a p2p latency for yggdrasil connections, you may take a look at [yggdrasil-jumper](https://github.com/one-d-wide/yggdrasil-jumper). It is a quiet simple standalone program that transparently implements dynamic peering, roughly as you describing, with no modification to the yggdrasil router.

**Comment by planetoryd** [comment] 2023-09-08 16:29
Yggdrasil is a routing protocol with fixed peerings. It's not a general protocol for end-to-end connectivity. You have some substantial misunderstanding about this project. There are other projects aimed at e2e connectivity with no peering constraints.

**Comment by oficsu** [comment] 2023-09-09 13:23
@neilalexander, 

> Simple answer of why we don't do this is because the whole purpose of Yggdrasil is to figure out how to efficiently route with the links we have been given

So, is it only a research project and no one expects it will be a mature project?

> If we add mechanisms to facilitate new peerings automatically then we are changing the scope of the project significantly

I think there are enough _users_ that already don't understand the scope of the project. And even more potential users find this project looking for a silver bullet that should solve their problems (but it isn't)

@planetoryd,

> There are other projects aimed at e2e connectivity with no peering constraints

I don't know any mature or even just really working project that you can "just use" _(except the very new yggdrasil-jumper, I'll look at it; I didn't even know this feature was possible outside of Yggdrasil itself)_

> Yggdrasil is a routing protocol with fixed peerings. It's not a general protocol for end-to-end connectivity. You have some substantial misunderstanding about this project

When you hear about Yggdrasil for the first time, it looks like a tool, a very cool silver bullet that can solve a bunch of different problems. _But when you are looking closer_, it turns out that every aspect of the project is not so simple, and you get disappointed with every attempt to solve your own issue with the tool

It allows you p2p connections, _but_ with a little different meaning of p2p than in other similar projects. It looks like a VPN, _but_ it isn't. It lets you connect to another device, _but_ it's unsafe by default, and you have to manage the security aspects (like firewalls; not a task for a regular user)

I can't insist on it, but, _maybe_, it's better  to be closer to user expectations? At least, shouldn't we mention yggdrasil-jumper in the Yggdrasil documentation? I don't know how it's possible to find it, even intentionally ¯\_(ツ)_/¯

**Comment by planetoryd** [comment] 2023-09-09 14:21
An overlay network with assumption of globally reachable internet would have a drastically different topology. The entire purpose, the algorithm being tested is based on the assumption that only a few peers are directly accessible. So, he's testing the algorithm under this particular assumption. Traffic gets relayed by peers, which gets the protocol tested. If traffic just reaches the peer directly every time you initiates a connection, there is no testing any more. It becomes a DHT at that time.

At some point it will be made into an actual product, or some people make another protocol and use its algo.

**Comment by NikitaPuzyryov** [comment] 2023-09-09 14:27
There will be no choice of peers if/when ygg _replaces_ the internet

**Comment by planetoryd** [comment] 2023-09-09 16:43
China, Iran, and Russia won't allow it. It's lucky enough TLS became widespread before China decided to up their firewall. They outright banned ECH.

**Comment by oficsu** [comment] 2023-09-09 16:59
> An overlay network with assumption of globally reachable internet would have a drastically different topology. The entire purpose, the algorithm being tested is based on the assumption that only a few peers are directly accessible. So, he's testing the algorithm under this particular assumption

@planetoryd, but can we think of it as an optional optimization layer (based on underlying protocol(s)) for Yggdrasil? We can continue to test Yggdrasil without the optimization, but keep an (experimental) option for end users

In any case, it might be better if each Yggdrasil peer could natively act as a STUN server (it already acts similar to TURN) at the protocol level to get rid of third-party stun servers from the yggdrasil-jumper configuration. It's great that we can implement this already, but wouldn't it be better if yggdrasil-jumper could rely only on Yggdrasil and not third-parties to implement this feature?

**Comment by iczelion** [comment] 2023-09-09 21:05
I would like to remind community members that Yggdrasil is not intended to solve your problems.

DNS is not the goal of Yggdrasil.
Firewall is not the goal of Yggdrasil.
Tunneling in the form of CKR is not the goal of Yggdrasil
Breaking through NAT is not the goal of Yggdrasil
Bypassing blockages and sledging are not the goal of Yggdrasil
STUN server is not Yggdrasil's goal

Stop flooding, please.

**Comment by neilalexander** [comment] 2023-10-21 20:29
Closing for reasons discussed earlier.

**Closed by neilalexander** 2023-10-21 20:29 UTC
