### ISSUE TITLE
Invalid Version hjson-go

### ISSUE THREAD

**Issue by GH0st3rs** [yggdrasil-network/yggdrasil-go#550] opened 2019-09-19 12:49 UTC
```diff
diff --git a/go.mod b/go.mod
index 5569496..d6d6b1e 100644
--- a/go.mod
+++ b/go.mod
@@ -3,7 +3,7 @@ module github.com/yggdrasil-network/yggdrasil-go
 require (
        github.com/gologme/log v0.0.0-20181207131047-4e5d8ccb38e8
        github.com/hashicorp/go-syslog v1.0.0
-       github.com/hjson/hjson-go v0.0.0-20181010104306-a25ecf6bd222
+       github.com/hjson/hjson-go v0.0.0-20181210174306-a25ecf6bd222
        github.com/kardianos/minwinsvc v0.0.0-20151122163309-cad6b2b879b0
        github.com/mitchellh/mapstructure v1.1.2
        github.com/songgao/packets v0.0.0-20160404182456-549a10cd4091
@@ -16,3 +16,5 @@ require (
        golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
        golang.org/x/text v0.3.2
 )
+
+go 1.13
diff --git a/go.sum b/go.sum
index 756ed5a..3987308 100644
--- a/go.sum
+++ b/go.sum
@@ -4,6 +4,8 @@ github.com/hashicorp/go-syslog v1.0.0 h1:KaodqZuhUoZereWVIYmpUgZysurB1kBLX2j0MwM
 github.com/hashicorp/go-syslog v1.0.0/go.mod h1:qPfqrKkXGihmCqbJM2mZgkZGvKG1dFdvsLplgctolz4=
 github.com/hjson/hjson-go v0.0.0-20181010104306-a25ecf6bd222 h1:xmvkbxXDeN1ffWq8kvrhyqVYAO2aXuRBsbpxVTR+JyU=
 github.com/hjson/hjson-go v0.0.0-20181010104306-a25ecf6bd222/go.mod h1:qsetwF8NlsTsOTwZTApNlTCerV+b2GjYRRcIk4JMFio=
+github.com/hjson/hjson-go v0.0.0-20181210174306-a25ecf6bd222 h1:AXARQ6sFKgTVEd8AO02tiPUvvOubnWZzl4OjBhgKtng=
+github.com/hjson/hjson-go v0.0.0-20181210174306-a25ecf6bd222/go.mod h1:qsetwF8NlsTsOTwZTApNlTCerV+b2GjYRRcIk4JMFio=
 github.com/kardianos/minwinsvc v0.0.0-20151122163309-cad6b2b879b0 h1:YnZmFjg0Nvk8851WTVWlqMC1ecJH07Ctz+Ezxx4u54g=
 github.com/kardianos/minwinsvc v0.0.0-20151122163309-cad6b2b879b0/go.mod h1:rUi0/YffDo1oXBOGn1KRq7Fr07LX48XEBecQnmwjsAo=
 github.com/mitchellh/mapstructure v1.1.2 h1:fmNYVwqnSfB9mZU6OS2O6GsXM+wcskZDuKQzvN1EDeE=
```

**Comment by GH0st3rs** [comment] 2019-09-19 12:50
```bash
$ ./build 
Building: yggdrasil
go: github.com/hjson/hjson-go@v0.0.0-20181210104306-a25ecf6bd222: invalid pseudo-version: does not match version-control timestamp (2018-12-10T17:43:06Z)
```

**Comment by neilalexander** [comment] 2019-09-19 12:51
Duplicate of #535 — fixed in `develop`.

**Closed by neilalexander** 2019-09-19 12:51 UTC

**Comment by neilalexander** [comment] 2019-09-19 13:09
Incidentally, we do have vendored sources of v0.3.8 which include a fix for this too:

https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.3.8/yggdrasil-0.3.8-vendor.tar.gz
