### ISSUE TITLE
Fails to start on systemd 243 when DynamicUser=true

### ISSUE THREAD

**Issue by gazally** [yggdrasil-network/yggdrasil-go#557] opened 2019-09-21 23:42 UTC
I'm working on packaging yggdrasil 0.3.8 for NixOS.  I'm creating a systemd service unit using the same set of sandboxing options as in #449, which includes `DynamicUser=true`.  Under those conditions, yggdrasil works with systemd 242 and fails with the new systemd 243:

```
systemd[1]: Started Yggdrasil Network Service.
yggdrasil[811]: 2019/09/21 14:59:33 Build name: yggdrasil
yggdrasil[811]: 2019/09/21 14:59:33 Build version: 0.3.8
yggdrasil[811]: 2019/09/21 14:59:33 Starting up...
yggdrasil[811]: 2019/09/21 14:59:33 Starting switch
yggdrasil[811]: 2019/09/21 14:59:33 Starting router
yggdrasil[811]: 2019/09/21 14:59:33 Startup complete
yggdrasil[811]: panic: permission denied
yggdrasil[811]: goroutine 1 [running]:
yggdrasil[811]: github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc00009fc50, 0xc000016768, 0x4, 0x0, 0xc00001c2a0, 0x27, 0xffff, 0xec062ce59ca8df00, 0x8a9f0619b6716784)
yggdrasil[811]:   /build/source/src/tuntap/tun_linux.go:26 +0x4c2
yggdrasil[811]: github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start(0xc00009fc50, 0xc000010250, 0x0)
yggdrasil[811]:   /build/source/src/tuntap/tun.go:140 +0x3f5
yggdrasil[811]: main.main()
yggdrasil[811]:   /build/source/cmd/yggdrasil/main.go:249 +0xf3d
```

If I remove `DynamicUser=true` from the service definition, then yggdrasil works with systemd 243.  I tried, with DynamicUser unset, adding in the set of options which are implied by DynamicUser according to the systemd.exec documentation (PrivateTmp, RemoveIPC, NoNewPrivileges, ProtectSystem, ProtectHome, RestrictSUIDSGID) and none of those made it fail.

**Comment by neilalexander** [comment] 2019-09-22 20:47
I’m not terribly familiar with systemd but if this worked in 242 and not in 243, is this a bug in systemd?

**Comment by gazally** [comment] 2019-09-22 21:50
The question that I don't know the answer to is whether it's a bug in systemd or a bug fix in systemd, since it's possible that 242 was allowing processes to do something they shouldn't and they fixed it in 243. Either way since systemd 243 is probably going into a lot of fall distro updates, I wanted to let you and anyone else writing a service unit for yggdrasil know what I found.

**Comment by Luzifer** [comment] 2019-09-22 22:51
Tried to reproduce on Arch and Yggdrasil 0.3.7 / develop (sadly I missed the chance to build 0.3.8 before Go1.13 broke the build) and wasn't able to:

```console
# systemctl --version
systemd 243 (243.0-1-arch)
```

```console
# cat /usr/lib/systemd/system/yggdrasil.service
[Unit]
Description=yggdrasil
Wants=network.target
After=network.target

[Service]
# --- 8< ---
# Removed duplicates: ProtectHome, ProtectSystem, Restart
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN
DynamicUser=true
MemoryDenyWriteExecute=true
PrivateTmp=true
ProtectControlGroups=true
ProtectKernelModules=true
ProtectKernelTunables=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=true
RestrictRealtime=true
RuntimeDirectory=yggdrasil
RuntimeDirectoryMode=0700
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @raw-io @resource
# --- >8 ---

Group=yggdrasiltmp # Set because of user/group collision with existing user
User=yggdrasiltmp # Set because of user/group collision with existing user
ProtectHome=true
ProtectSystem=true
SyslogIdentifier=yggdrasil
ExecStartPre=/bin/sh -ec "if ! test -s /etc/yggdrasil.conf; \
                then umask 077; \
                yggdrasil -genconf > /etc/yggdrasil.conf; \
                echo 'WARNING: A new /etc/yggdrasil.conf file has been generated.'; \
            fi"
ExecStart=/usr/bin/yggdrasil -useconffile /etc/yggdrasil.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target
```

```console
# grep Admin /etc/yggdrasil.conf 
  AdminListen: unix:///var/run/yggdrasil/yggdrasil.sock
```

Had to adjust one more thing: Needed to make the `/etc/yggdrasil.conf` world-readable as of the random user being created during start and destroyed during stop.

@gazally please paste a full copy of your `yggdrasil.service` or check whether my version above matches yours… If those match for the important parts still there could be a patch to systemd in Arch / NixOS breaking / repairing stuff…

**Comment by gazally** [comment] 2019-09-23 16:48
I tried your `yggdrasil.service` with 0.3.7 on NixOS systemd 243 and got the same result.  But your suggestion to look for patches is a good one.  Turns out that NixOS has 25 patches applied on top of systemd so it's definitely possible that the fault is in the patch set.  I will investigate further in that direction.

What's the Go 1.13 issue?

**Comment by Luzifer** [comment] 2019-09-23 17:43
These are the patches in Arch (according to the commits nothing changed for 243): https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/systemd

The Go 1.13 issue is this one (fixed in `develop`): https://github.com/yggdrasil-network/yggdrasil-go/issues/535

**Comment by neilalexander** [comment] 2019-11-20 14:33
Is this still an issue? Please feel free to close if not.

**Comment by neilalexander** [comment] 2020-02-16 14:51
Closing due to inactivity. Please reopen if it's still an issue we need to look at.

**Closed by neilalexander** 2020-02-16 14:51 UTC
