### ISSUE TITLE
Version 0.3.16 service does not start

### ISSUE THREAD

**Issue by MakeHorizont** [yggdrasil-network/yggdrasil-go#771] opened 2021-03-20 19:02 UTC
![photo_2021-03-20_22-00-28](https://user-images.githubusercontent.com/30184045/111882652-b4380700-89c7-11eb-8a69-4a7d334b32b8.jpg)

application installation is stopped by this popup. Administrator rights are present, permission to install is granted. Version 0.3.15 was installed without problems.

Version 0.3.16 was installed without problems on top of Version 0.3.15.
When installing Version 0.3.16 from 0, an error popped up

**Comment by dancyuser** [comment] 2021-04-10 16:13
Yep, this is also an issue for me

**Comment by neilalexander** [comment] 2021-04-17 10:33
Is there anything in the Event Viewer that describes what is going wrong?

**Comment by dimio** [comment] 2021-04-21 07:24
I have same installing problem on Windows 10, Yggdrasil 0.3.16-x64.

**Comment by loskiq** [comment] 2021-05-15 08:54
when will this problem be fixed? i can't use Yggdrasil!

**Comment by zhoreeq** [comment] 2021-05-15 10:49
As a workaround, some users say they install 0.3.15 first and then install 0.3.16 

@loskiq AFAIK there are no Windows developers in the project to solve Windows issues

**Comment by M0rdecay** [comment] 2021-05-24 15:51
It looks like installer does not create files in `%ALLUSERSPROFILE%\Yggdrasil\yggdrasil.conf`, than installation will not completed (it requires service successful start)

**Comment by bagomot** [comment] 2021-06-05 08:51
The `C:\ProgramData\Yggdrasil` directory is not created. Create manually and in it create and fill the settings file `yggdrasil.conf`. The service will then be able to start.

**Comment by vikulin** [comment] 2021-06-12 20:40
Attaching msi installation logs for 0.3.15 and 0.4.0rc:

[ygg-0.3.15.log](https://github.com/yggdrasil-network/yggdrasil-go/files/6642869/ygg-0.3.15.log)

[ygg-0.40rc.log](https://github.com/yggdrasil-network/yggdrasil-go/files/6642868/ygg-0.40rc.log)

**Comment by vikulin** [comment] 2021-06-13 00:30
Probably caused by https://gitlab.gnome.org/GNOME/msitools/-/issues/12

**Comment by neilalexander** [comment] 2021-07-07 23:13
I think this is fixed in v0.4. Please reopen if not.

**Closed by neilalexander** 2021-07-07 23:13 UTC
Labels: windows

**Comment by kden416** [comment] 2024-01-28 12:00
Same problem with installation. Ver. 0.5.5-x64 Win 10

**Comment by romanov** [comment] 2024-05-13 12:17
Disable antivirus
