### ISSUE TITLE
deadlock with ckr

### ISSUE THREAD

**Issue by wfleurant** [yggdrasil-network/yggdrasil-go#565] opened 2019-10-02 19:26 UTC
hello,

i've got 0.3.9 with ./build -d and pprof goroutine output below.  

with cryptokey routing 0.0.0.0/0 it is possible to cause some sort of deadlock when performing iperf over the internet or simply visiting a speed test website. speeds ramp up but all packets stop processing. 

```
% ~ iperf3 -c somebox
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  3.65 MBytes  30.6 Mbits/sec    0    165 KBytes       
[  5]   1.00-2.00   sec  30.1 MBytes   253 Mbits/sec    0   1.53 MBytes       
[  5]   2.00-3.00   sec  6.25 MBytes  52.4 Mbits/sec    2   1.41 KBytes       
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
```

below goroutine trace is relevant differences before / after triggering deadlock  
```
goroutine 97525 [IO wait]:
internal/poll.runtime_pollWait(0x7ff5b49b4540, 0x72, 0xc000316e18)
    /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000769d8, 0x72, 0xffffffffffffff01, 0x9d7da0, 0xce4658)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000769d8, 0xc000a9a001, 0x1000d, 0x1000d)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0000769c0, 0xc000a9a000, 0x1000d, 0x1000d, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
os.(*File).read(0xc00000e0e8, 0xc000a9a000, 0x1000d, 0x1000d, 0x101, 0xc000316ea8, 0xc000316f20)
    /usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc00000e0e8, 0xc000a9a000, 0x1000d, 0x1000d, 0x1000d, 0x1000d, 0x0)
    /usr/local/go/src/os/file.go:108 +0x69
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*tunReader)._read(0xc0001d2760)
    .../yggdrasil-go/src/tuntap/iface.go:113 +0x80
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*tunReader)._read-fm()
    .../yggdrasil-go/src/tuntap/iface.go:121 +0x2a
github.com/Arceliar/phony.(*Inbox).run(0xc0001d2760)
    .../pkg/mod/github.com/!arceliar/phony@v0.0.0-20190907031509-af5bdbeecab6/actor.go:96 +0x8d
created by github.com/Arceliar/phony.(*Inbox).restart
    .../pkg/mod/github.com/!arceliar/phony@v0.0.0-20190907031509-af5bdbeecab6/actor.go:127 +0x3f

---  8<  8<  8<  ---

goroutine 129966 [IO wait]:
internal/poll.runtime_pollWait(0x7ff5b4942370, 0x72, 0xc0013f0e58)
    /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001f2118, 0x72, 0xffffffffffffff00, 0x9d7da0, 0xce4658)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001f2118, 0xc0005ac100, 0x1, 0x1)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0001f2100, 0xc0005ac101, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0001f2100, 0xc0005ac101, 0x1, 0x1, 0xc0007ba060, 0x0, 0xc0007ba060)
    /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e038, 0xc0005ac101, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0005ac0f0)
    /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
    /usr/local/go/src/net/http/server.go:672 +0xd2

```

other side notes
- yggdrasilctl stops responding (tried calling getpeers)
- non ckr traffic to directly connected nodes stops (not only ckr)
- iperf to non ckr traffic does not trigger deadlock (bug seems ckr specific)

**Comment by Arceliar** [comment] 2019-10-03 02:53
A few comments from testing on my side:
1. I'm able to reproduce this in network namespaces using CKR if I reduce the bandwidth between namespaces to something low an reduce the MTU. I.e. make sure I can send packets much faster than the "network" can handle them.
2. I was not able to reproduce this without CKR, or with large MTU (which wouldn't work outside of a controlled environment) and no rate limit.
3. Looking at the goroutine dump, I see no differences between when things are in a working or a broken state, which is odd.
4. So far I have *not* been able to reproduce the behavior where `yggdrasilctl` blocks: everything I tested still responds, including things like checking the local CKR prefixes, so it doesn't seem to be a deadlock there.

**Comment by Arceliar** [comment] 2019-10-03 03:10
Aha, I think I found it!

https://github.com/yggdrasil-network/yggdrasil-go/blob/0f99d590a1c2592e333a51a71b4536aebaea5cc0/src/tuntap/conn.go#L96

That call to `RemoteAddr` (and one other call in the same file) uses `phony.Block` under the hood, so it's not safe to call from an async actor.

**Comment by Arceliar** [comment] 2019-10-05 16:29
Should be fixed in the latest develop (feel free to reopen the issue if it's not).

**Closed by Arceliar** 2019-10-05 16:29 UTC
