### ISSUE TITLE
Yggdrasil does not automatically use IPv6

### ISSUE THREAD

**Issue by marek22k** [yggdrasil-network/yggdrasil-go#980] opened 2022-11-08 14:44 UTC
Hello,

I have two IPv6-only VM. I already noticed this behavior with the first one, but I thought it was a bug in the VM. However, today I got another IPv6-only VM in which this behavior also occurs.
There is no IPv4 route:
```
# ip r g 1.1.1.1
RTNETLINK answers: Network is unreachable
```

Yggdrasil resolves the DNS name and tries to use only the IPv4, but not the IPv6. My peers:
```
    tcp://p2p-node.de:1337?key=000000d80a2d7b3126ea65c8c08fc751088c491a5cdd47eff11c86fa1e4644ae
    tls://p2p-node.de:1338?key=000000d80a2d7b3126ea65c8c08fc751088c491a5cdd47eff11c86fa1e4644ae
    tcp://ygg1.mk16.de:1337?key=0000000087ee9949eeab56bd430ee8f324cad55abf3993ed9b9be63ce693e18a
    tls://ygg1.mk16.de:1338?key=0000000087ee9949eeab56bd430ee8f324cad55abf3993ed9b9be63ce693e18a
    tcp://94.130.203.208:5999
    tcp://ygg.mkg20001.io:80
    tls://ygg.mkg20001.io:443
    tcp://yggdrasil.su:62486
    tls://yggdrasil.su:62586
    tls://vpn.ltha.de:443?key=0000006149970f245e6cec43664bce203f2514b60a153e194f31e2b229a1339d
    tcp://phrl42.ydns.eu:8842
```
Some of these also have IPv6 addresses (I'm sure of two, as they are my own).

Log:
```
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Your public key is a5575fb5e73326e45524063a8ac61de262debad4e350619cb5ffda815a07fa35
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Your IPv6 address is 200:b551:4094:3199:b237:55b7:f38a:ea73
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Your IPv6 subnet is 300:b551:4094:3199::/64
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TCP p2p-node.de:1337: dial tcp 5.45.109.122:1337: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TLS ygg1.mk16.de:1338: dial tcp 5.252.226.123:1338: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TLS vpn.ltha.de:443: dial tcp 168.119.169.163:443: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TCP ygg1.mk16.de:1337: dial tcp 5.252.226.123:1337: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TCP phrl42.ydns.eu:8842: dial tcp 87.146.221.144:8842: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TCP yggdrasil.su:62486: dial tcp 94.130.176.250:62486: connect: network is unreachable
Nov 08 14:32:17 AS202952 yggdrasil[9031]: 2022/11/08 14:32:17 Failed to dial TLS yggdrasil.su:62586: dial tcp 94.130.176.250:62586: connect: network is unreachable
```

**Comment by jcgruenhage** [comment] 2022-11-20 22:27
@neilalexander is this a dupe of #956?

**Comment by neilalexander** [comment] 2022-11-20 23:21
More than likely yes.

**Closed** 2023-02-26 21:24 UTC
